### PR TITLE
Use separate layers for each add layer

### PR DESCRIPTION
**Pull request by masatoprc**

### CODE REVIEW

**Comment by lintool** [comment]
My vote is for spaces!

**Comment by masatoprc** [comment]
@daemon @lintool I will update the spaces when I am back to Canada. Don't have access to a computer now.

**Comment by ljj7975** [comment]
@daemon @lintool I caught that as well but since he will be out, I told him that I will fix it up. I will do it.

**Comment by ljj7975** [comment]
cleaned up code, improved UI for saving/loading, linked loaded model with prediction

**Pull request merged**
